use_frameworks!

platform :ios, '9.0'

target 'PapilonNFCReaderiOS_Example' do
  pod 'PapilonNFCReaderiOS', :path => '../'

  target 'PapilonNFCReaderiOS_Tests' do
    inherit! :search_paths

    
  end
end
